### ISSUE TITLE
数据处理的过程

### ISSUE THREAD

**Issue by UnseenAnchor** [BGI-DEV-REG/ARTISTA#1]
感谢大佬贡献精致的论文，我想请教一下这个数据处理的过程代码，stereo-seq 到最后包含以下信息的axolotl_2DPI.h5ad
AnnData object with n_obs × n_vars = 7668 × 27324
    obs: 'CellID', 'spatial_leiden_e30_s8', 'Batch', 'cell_id', 'seurat_clusters', 'inj_uninj', 'D_V', 'inj_M_L', 'Annotation'
    var: 'Axolotl_ID', 'hs_gene'
    uns: 'Annotation_colors', '__type', 'color_key'
    obsm: 'X_spatial', 'spatial'
    layers: 'counts', 'log1p'
    obsp: 'connectivities', 'distances', 'spatial_connectivities', 'spatial_distances'
数据经过了哪些处理？

**Comment by WangShuai-3** [comment]
抱歉，回复迟了。stereo-seq早期版本会给出空间基因表达矩阵文件gem，经过细胞核染色图像配准和细胞分割后可得到空间单细胞基因表达矩阵文件scgem，并最终处理生成Seurat对象，相关流程涉及代码存储在 https://github.com/BGI-DEV-REG/ARTISTA/tree/main/code/RYtools 中。数据经过Seurat SCTransform、Seurat标准分析流程以及使用python进行SCC空间聚类，相关参数及引用见文章Method部分，以及本仓库的其他代码文件，如 https://github.com/BGI-DEV-REG/ARTISTA/blob/main/code/Figure1C_Brain_region.py 。希望对您有所帮助！

**Comment by UnseenAnchor** [comment]
感谢感谢感谢
